---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: shared-services
  labels:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/part-of: shared-services
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pyroscope
  ports:
    - name: http
      port: 4040
      targetPort: http
      protocol: TCP
