apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.name }}
spec:
  dataVolumeTemplates:
    - metadata:
        name: {{ .Values.name }}
      spec:
        sourceRef:
          kind: DataSource
          {{- if and (eq .Values.rhelVersion "9") (eq .Values.arch "amd64") }}
          name: rhel9-amd64
          {{- else }}
          name: rhel{{ .Values.rhelVersion }}
          {{- end }}
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: {{ .Values.storageSize | default "30Gi" }}
  preference:
    name: rhel.{{ .Values.rhelVersion }}
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      {{- if .Values.arch }}
      architecture: {{ .Values.arch }}
      {{- end }}
      domain:
        {{- if or (eq .Values.rhelVersion "9") (eq .Values.rhelVersion "10") }}
        features:
          smm:
            enabled: false
        firmware:
          bootloader:
            efi:
              secureBoot: false
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.cores }}
            memory: {{ .Values.memory }}
          limits:
            cpu: {{ .Values.cores }}
            memory: {{ .Values.memory }}
        devices:
          autoattachPodInterface: false
          autoattachVSOCK: true
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      {{- if .Values.arch }}
      nodeSelector:
        kubernetes.io/arch: {{ .Values.arch }}
      {{- end }}
      volumes:
        - dataVolume:
            name: {{ .Values.name }}
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - default
                - name: cloud-user
                  groups: wheel
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  lock_passwd: false
                  plain_text_passwd: testpass123
                  ssh_authorized_keys:
                    {{- range .Values.sshKeys }}
                    - {{ . }}
                    {{- end }}
              ssh_pwauth: true
          name: cloudinitdisk
