apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      openshift.io/host.generated: "true"
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central
    namespace: stackrox
  spec:
    host: central-stackrox.apps.rosa.kl-01-21-circus.wuui.p3.openshiftapps.com
    port:
      targetPort: https
    tls:
      termination: passthrough
    to:
      kind: Service
      name: central
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2026-01-21T19:04:49Z"
        status: "True"
        type: Admitted
      host: central-stackrox.apps.rosa.kl-01-21-circus.wuui.p3.openshiftapps.com
      routerCanonicalHostname: router-default.apps.rosa.kl-01-21-circus.wuui.p3.openshiftapps.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-mtls
    namespace: stackrox
  spec:
    host: central.stackrox
    port:
      targetPort: https
    tls:
      termination: passthrough
    to:
      kind: Service
      name: central
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2026-01-21T19:04:49Z"
        status: "True"
        type: Admitted
      host: central.stackrox
      routerCanonicalHostname: router-default.apps.rosa.kl-01-21-circus.wuui.p3.openshiftapps.com
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
